let MoodData = {
  Clear: [
    "Sunny",
    "Happy",
    "Energetic",
    "Productive",
    "Active",
    "Optimistic",
    "Cheerful",
    "Vibrant",
    "Refreshed",
    "Adventurous",
    "Inspired",
    "Free",
    "Peaceful",
    "Hopeful",
    "Confident",
    "Radiant",
    "Blissful",
    "Dynamic",
    "Focused",
    "Relieved",
    "Powerful",
    "Determined",
    "Accomplished",
    "Jubilant",
    "Playful",
    "Serene",
  ],

  Clouds: [
    "Calm",
    "Relaxed",
    "Cozy",
    "Thoughtful",
    "Contemplative",
    "Melancholy",
    "Soothing",
    "Dreamy",
    "Introspective",
    "Comfortable",
    "Mystical",
    "Mellow",
    "Serene",
    "Comforted",
    "Creative",
    "Peaceful",
    "Content",
    "Reflective",
    "Melancholic",
    "Wistful",
    "Nostalgic",
    "Gentle",
  ],

  Rain: [
    "Peaceful",
    "Romantic",
    "Reflective",
    "Nostalgic",
    "Rejuvenated",
    "Sad",
    "Blissful",
    "Cleansed",
    "Tranquil",
    "Relaxed",
    "Melancholic",
    "Refreshed",
    "Pensive",
    "Content",
    "Cozy",
    "Soothed",
    "Calm",
    "Comforted",
    "Renewed",
    "Centered",
    "Inspired",
  ],

  Snow: [
    "Playful",
    "Festive",
    "Nostalgic",
    "Cozy",
    "Reflective",
    "Serene",
    "Whimsical",
    "Joyful",
    "Blissful",
    "Magical",
    "Peaceful",
    "Enchanted",
    "Refreshed",
    "Radiant",
    "Wonder-filled",
    "Childlike",
    "Rejuvenated",
    "Invigorated",
    "Inspired",
    "Dreamy",
  ],
  
  else: [
    "Alert",
    "Energetic",
    "Stimulated",
    "Calm",
    "Introspective",
    "Thoughtful",
    "Peaceful",
    "Serene",
    "Tranquil",
    "Sweaty",
    "Thirsty",
    "Tired",
    "Chilly",
    "Numb",
    "Crisp",
    "Muggy",
    "Uncomfortable",
    "Damp",
    "Anxious",
    "Tense",
    "Restless",
  ],
};

export default MoodData;
